### ISSUE TITLE
About the criterion in paper, such as Inter F1, Intra F1 and LT F1

### ISSUE THREAD

**Issue by LawsonAbs** [tonytan48/Re-DocRED#1]
Nice work! 
Thank your contribution to Document Level Relation extraction. However, the public dataset is important is open evaluation criteria. The NLP community would be greatful  if you can release your code about the evaluation.

**Comment by tonytan48** [comment]
Thank you for your interest in our work! I have just uploaded the evaluation script used in our paper. You can just change the function name and variable names accordingly.

**Comment by LawsonAbs** [comment]
Thank you again! Best wishes for you.
